[package]
name = "detect-lang"
version = "0.1.0"
authors = ["Christian Vallentin"]
edition = "2018"
description = "Language detection given paths and extensions"
keywords = ["language", "lang", "language name", "language id", "lang id", "path", "extension"]
categories = ["algorithms"]
license = "MIT"
repository = "https://github.com/vallentin/detect-lang"
homepage = "https://github.com/vallentin/detect-lang"
documentation = "https://docs.rs/detect_lang"
readme = "README.md"

[dependencies]
