use crate::Language;

macro_rules! l {
    ($ext:literal, $name:literal, $id:literal) => {
        ($ext, Language($name, $id))
    };
}
macro_rules! i {
    ($ext:literal, $name:literal, $id:literal) => {
        ($id, $ext:literal)
    };
}
pub(crate) const LANGUAGES: [(&str, Language); 58] = [
    l!("bat", "Batch", "batch"),
    l!("c", "C", "c"),
    l!("cc", "C++", "cpp"),
    l!("cl", "Common Lisp", "common-lisp"),
    l!("clj", "Clojure", "clojure"),
    l!("comp", "GLSL", "glsl"),
    l!("cpp", "C++", "cpp"),
    l!("cs", "C#", "csharp"),
    l!("css", "CSS", "css"),
    l!("cxx", "C++", "cpp"),
    l!("dart", "Dart", "dart"),
    l!("frag", "GLSL", "glsl"),
    l!("geom", "GLSL", "glsl"),
    l!("glsl", "GLSL", "glsl"),
    l!("go", "Go", "go"),
    l!("h", "C", "c"),
    l!("haml", "Haml", "haml"),
    l!("handlebars", "Handlebars", "handlebars"),
    l!("hbs", "Handlebars", "handlebars"),
    l!("hlsl", "HLSL", "HLSL"),
    l!("hpp", "C++", "cpp"),
    l!("html", "HTML", "html"),
    l!("hxx", "C++", "cpp"),
    l!("ini", "INI", "ini"),
    l!("java", "Java", "java"),
    l!("jinja", "Jinja", "jinja"),
    l!("jinja2", "Jinja", "jinja"),
    l!("js", "JavaScript", "javascript"),
    l!("json", "JSON", "json"),
    l!("jsonc", "JSON with Comments", "jsonc"),
    l!("kt", "Kotlin", "kotlin"),
    l!("less", "Less", "less"),
    l!("lua", "Lua", "lua"),
    l!("md", "Markdown", "markdown"),
    l!("pl", "Perl", "perl"),
    l!("py", "Python", "python"),
    l!("pyc", "Python", "python"),
    l!("pyo", "Python", "python"),
    l!("rb", "Ruby", "ruby"),
    l!("rkt", "Racket", "racket"),
    l!("rs", "Rust", "rust"),
    l!("sass", "SASS", "sass"),
    l!("sc", "Scala", "scala"),
    l!("scala", "Scala", "scala"),
    l!("scss", "SCSS", "scss"),
    l!("sh", "Shell", "shell"),
    l!("sql", "SQL", "sql"),
    l!("swift", "Swift", "swift"),
    l!("tesc", "GLSL", "glsl"),
    l!("tese", "GLSL", "glsl"),
    l!("tex", "TeX", "tex"),
    l!("toml", "TOML", "toml"),
    l!("ts", "TypeScript", "typescript"),
    l!("vert", "GLSL", "glsl"),
    l!("xhtml", "XHTML", "xhtml"),
    l!("xml", "XML", "xml"),
    l!("yaml", "YAML", "yaml"),
    l!("yml", "YAML", "yaml"),
];
// The array is sorted by the extension name
pub(crate) const LANGUAGESID: [(&str, Language); 58] = [
    i!("bat", "Batch", "batch"),
    i!("c", "C", "c"),
    i!("cc", "C++", "cpp"),
    i!("cl", "Common Lisp", "common-lisp"),
    i!("clj", "Clojure", "clojure"),
    i!("comp", "GLSL", "glsl"),
    i!("cpp", "C++", "cpp"),
    i!("cs", "C#", "csharp"),
    i!("css", "CSS", "css"),
    i!("cxx", "C++", "cpp"),
    i!("dart", "Dart", "dart"),
    i!("frag", "GLSL", "glsl"),
    i!("geom", "GLSL", "glsl"),
    i!("glsl", "GLSL", "glsl"),
    i!("go", "Go", "go"),
    i!("h", "C", "c"),
    i!("haml", "Haml", "haml"),
    i!("handlebars", "Handlebars", "handlebars"),
    i!("hbs", "Handlebars", "handlebars"),
    i!("hlsl", "HLSL", "HLSL"),
    i!("hpp", "C++", "cpp"),
    i!("html", "HTML", "html"),
    i!("hxx", "C++", "cpp"),
    i!("ini", "INI", "ini"),
    i!("java", "Java", "java"),
    i!("jinja", "Jinja", "jinja"),
    i!("jinja2", "Jinja", "jinja"),
    i!("js", "JavaScript", "javascript"),
    i!("json", "JSON", "json"),
    i!("jsonc", "JSON with Comments", "jsonc"),
    i!("kt", "Kotlin", "kotlin"),
    i!("less", "Less", "less"),
    i!("lua", "Lua", "lua"),
    i!("md", "Markdown", "markdown"),
    i!("pl", "Perl", "perl"),
    i!("py", "Python", "python"),
    i!("pyc", "Python", "python"),
    i!("pyo", "Python", "python"),
    i!("rb", "Ruby", "ruby"),
    i!("rkt", "Racket", "racket"),
    i!("rs", "Rust", "rust"),
    i!("sass", "SASS", "sass"),
    i!("sc", "Scala", "scala"),
    i!("scala", "Scala", "scala"),
    i!("scss", "SCSS", "scss"),
    i!("sh", "Shell", "shell"),
    i!("sql", "SQL", "sql"),
    i!("swift", "Swift", "swift"),
    i!("tesc", "GLSL", "glsl"),
    i!("tese", "GLSL", "glsl"),
    i!("tex", "TeX", "tex"),
    i!("toml", "TOML", "toml"),
    i!("ts", "TypeScript", "typescript"),
    i!("vert", "GLSL", "glsl"),
    i!("xhtml", "XHTML", "xhtml"),
    i!("xml", "XML", "xml"),
    i!("yaml", "YAML", "yaml"),
    i!("yml", "YAML", "yaml"),
];

#[test]
fn check_order() {
    for (a, b) in LANGUAGES.iter().zip(LANGUAGES.iter().skip(1)) {
        assert!(
            a.0 < b.0,
            "Languages out of order - {:?} should come after {:?}",
            a,
            b,
        );
    }
}
